# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'basic_image.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(991, 623)
        self.dockWidget_raw = QtWidgets.QDockWidget(Form)
        self.dockWidget_raw.setGeometry(QtCore.QRect(30, 70, 701, 491))
        self.dockWidget_raw.setObjectName("dockWidget_raw")
        self.dockWidgetContents_7 = QtWidgets.QWidget()
        self.dockWidgetContents_7.setObjectName("dockWidgetContents_7")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.dockWidgetContents_7)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.graphics_raw = QtWidgets.QGraphicsView(self.dockWidgetContents_7)
        self.graphics_raw.setObjectName("graphics_raw")
        self.gridLayout_22.addWidget(self.graphics_raw, 0, 0, 1, 1)
        self.dockWidget_raw.setWidget(self.dockWidgetContents_7)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.dockWidget_raw.setWindowTitle(_translate("Form", "FasterRCNN检测"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
